- hosts: all
  gather_facts: no
  remote_user: ustudy
  become: true
  become_method: sudo
  ignore_unreachable: yes

  tasks:



              - name: restart nimble
              ansible.builtin.service:
              name: nimble
              state: restarted
