- hosts: ustudy
  gather_facts: no
  become: yes
  ignore_unreachable: true
  ignore_errors: true

  handlers:
       - name: Stop nimble service
         ansible.builtin.service:
                  name: nimble
                  state: stopped
